- name: SSH | Remove PermitRootLogin line
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^#?(PermitRootLogin)"
    state: absent
  when: disable_root_login == True
  notify:
    - Restart sshd service

- name: SSH | Remove PermitEmptyPasswords line
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^#?(PermitEmptyPasswords)"
    state: absent
  notify:
    - Restart sshd service

- name: SSH | Remove Port line
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^#Port"
    state: absent
  notify:
    - Restart sshd service

- name: SSH | Remove ListenAddress line
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^#ListenAddress"
    state: absent
  notify:
    - Restart sshd service

- name: SSH | Remove PasswordAuthentication line
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^#?(PasswordAuthentication)"
    state: absent
  when: permit_only_ssh_key == True
  notify:
    - Restart sshd service

- name: SSH | Remove UsePAM line
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "UsePAM"
    state: absent
  notify:
    - Restart sshd service

- name: SSH | Remove IgnoreRhosts line
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "IgnoreRhosts"
    state: absent
  notify:
    - Restart sshd service

- name: SSH | Remove Protocol line
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^#Protocol"
    state: absent
  notify:
    - Restart sshd service

- name: SSH | Remove PubkeyAuthentication line
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^#PubkeyAuthentication"
    state: absent
  notify:
    - Restart sshd service

- name: SSH | Hardening SSH configuration
  blockinfile:
    dest: "{{ sshd_config_file }}"
    insertafter: "# semanage port"
    marker: "#{mark}ANSIBLE MANAGED BLOCK"
    state: present
    block: |
      Port {{ ssh_port }}
      UsePAM no
      Protocol 2
      IgnoreRhosts yes
      PermitRootLogin no
      PermitEmptyPasswords no
      PubkeyAuthentication yes
      PasswordAuthentication no
  notify:
    - Restart sshd service
